1d Array
Create a 1-dimensional NumPy array with elements [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
Calculate the sum and average of the array elements.
Multiply the array by a scalar value of 3.
Slice the array to select elements from the 3rd to the 7th position.
Compute the sum and average of the sliced array

Multi-dimensional array
Create a 3x3 matrix with the following rows in order: {3,4,5} {6,7,8} {9,1,2}
Print the element in the second row, third column.
Print the second row
Print the second column
Compute the transpose of the matrix

Concatenation
Create two 1-d arrays: [5,1,4,2] and [6,10,11,7]
Concatenate the two arrays
Sort the new array from lowest to highest
Split the result from the previous step into two equal sized arrays

Mathematical functions
Create an array with values from 0 to 4*pi in increments of pi/2 (pi refers to the mathematical constant  π)
Compute an array that applies the mathematical sin function to the original array
Do the same for the following mathematical functions: cos, log, exp
Compute the mean, median, and standard deviation of each resultant array

Boolean Indexing and Filtering
Create a 1-d array with all multiples of 5 from 15 to 80, and also include 12
Create a boolean array that identifies elements which are greater than 25
Use that boolean array to filter out elements greater than 25 from the original array.

In [5]:
# 1d Array
# Create a 1-dimensional NumPy array with elements [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
# Calculate the sum and average of the array elements.
# Multiply the array by a scalar value of 3.
# Slice the array to select elements from the 3rd to the 7th position.
# Compute the sum and average of the sliced array

import numpy as np
array_1D = np.arange(1,11)
print(array_1D)
one_d_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
total = sum(one_d_array)
avg = np.mean(one_d_array)
times_3 = 3 * one_d_array
slice_3_7 = one_d_array[2:7]
slice_total = sum(slice_3_7)
slice_avg = np.mean(slice_3_7)
print(total)
print(avg)
print(times_3)
print(slice_3_7)
print(slice_total)
print(slice_avg)

[ 1  2  3  4  5  6  7  8  9 10]
55
5.5
[ 3  6  9 12 15 18 21 24 27 30]
[3 4 5 6 7]
25
5.0


In [4]:
array_1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
# Multi-dimensional array
# Create a 3x3 matrix with the following rows in order: {3,4,5} {6,7,8} {9,1,2}
# Print the element in the second row, third column.
# Print the second row
# Print the second column
# Compute the transpose of the matrix

array_3D = np.array([[3,4,5], [6,7,8],[9,1,2]])
print("2nd Row, 3rd Column: ", array_3D[1,2])
print("2nd Row: ", array_3D[1])
print("2nd Column: ", array_3D[:,1])
transpose = array_3D.T
display("Transpose: ", transpose)


2nd Row, 3rd Column:  8
2nd Row:  [6 7 8]
2nd Column:  [4 7 1]


'Transpose: '

array([[3, 6, 9],
       [4, 7, 1],
       [5, 8, 2]])

In [45]:
# Concatenation
# Create two 1-d arrays: [5,1,4,2] and [6,10,11,7]
# Concatenate the two arrays
# Sort the new array from lowest to highest
# Split the result from the previous step into two equal sized arrays

arr1 = np.array([5, 1, 4, 2])
arr2 = np.array([6, 10, 11, 7])
both = arr1 + arr2
print(both)
sorted_array = np.sort(both)
print(sorted_array)
split_arr1 = np.array_split(sorted_array, 2)
print(split_arr)
#OR
split_arr2 = np.array(sorted_array[0],sorted_array[1])
print(split_arr[0][1])


[11 11 15  9]
[ 9 11 11 15]
[array([ 9, 11]), array([11, 15])]
11


In [6]:
# Mathematical functions
# Create an array with values from 0 to 4*pi in increments of pi/2 (pi refers to the mathematical constant  π)
# Compute an array that applies the mathematical sin function to the original array
# Do the same for the following mathematical functions: cos, log, exp
# Compute the mean, median, and standard deviation of each resultant array
import math as m

pi_array = []  # np.array(m.pi/2 * i for i in range(8))
for i in range(0, 9):
    pi_array.append(i * m.pi / 2)
pi_array = np.array(pi_array)
#Simpler way to make array
new_pi_array  = np.arange(0,4*m.pi+1,m.pi/2)
print("Pi values array")
print(pi_array)
sin_array = np.sin(pi_array)
print(50 * "-")
print("SIN values array")
print(sin_array)
cos_array = np.cos(pi_array)
print(50 * "-")
print("COS values array")
print(cos_array)
log_array = np.log(pi_array)
print(50 * "-")
print("Log values array")
# for i in log_array:
try:
    print(log_array)
except:
    "divide by zero"
print(50 * "-")
print("Log values array")
exp_array = np.exp(pi_array)
print(exp_array)
all_arrays = list([pi_array, sin_array, cos_array, log_array, exp_array])
for arr in all_arrays:
    print("Avg: ", np.mean(arr))
    print("Med: ", np.median(arr))
    print("St Dev: ", np.std(arr))
# print("Averages: ",np.mean(all_arrays))

Pi values array
[ 0.          1.57079633  3.14159265  4.71238898  6.28318531  7.85398163
  9.42477796 10.99557429 12.56637061]
--------------------------------------------------
SIN values array
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16  1.0000000e+00  3.6739404e-16 -1.0000000e+00
 -4.8985872e-16]
--------------------------------------------------
COS values array
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00  3.0616170e-16 -1.0000000e+00 -4.2862638e-16
  1.0000000e+00]
--------------------------------------------------
Log values array
[      -inf 0.45158271 1.14472989 1.55019499 1.83787707 2.06102062
 2.24334217 2.39749285 2.53102425]
--------------------------------------------------
Log values array
[1.00000000e+00 4.81047738e+00 2.31406926e+01 1.11317778e+02
 5.35491656e+02 2.57597050e+03 1.23916478e+04 5.96097415e+04
 2.86751313e+05]
Avg:  6.283185307179587
Med:  6.283185307179586
St Dev:  4.055778675973612
Avg:  -

/var/folders/jt/xt1b3v5j4171llx14wtwgmpc0000gn/T/ipykernel_15584/2380600262.py:24: RuntimeWarning: divide by zero encountered in log
  log_array = np.log(pi_array)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/numpy/core/_methods.py:173: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)


In [ ]:
pi = 3.14
valuesArray = np.arange(0, (pi * 4 + pi / 2), pi / 2)

In [7]:
#MY FIRST,CLUNKY SOLUTION
# Boolean Indexing and Filtering
# Create a 1-d array with all multiples of 5 from 15 to 80, and also include 12
# Create a boolean array that identifies elements which are greater than 25
# Use that boolean array to filter out elements greater than 25 from the original array.
new_arr = [12]
for i in range(15, 81, 5):
    new_arr.append(i)
print("1).  First Array: ", new_arr)
bool_arr = []
for i in new_arr:
    if i > 25:
        bool_arr.append(True)
    else:
        bool_arr.append(False)
print("2).  Boolean Array: ",bool_arr)
newer_arr = list(zip(new_arr, bool_arr))
keep = []
for i, j in newer_arr:
    if j == True:
        keep.append(i)
print("3).  Filtered Array: ", keep)

1).  First Array:  [12, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80]
2).  Boolean Array:  [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True]
3).  Filtered Array:  [30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80]


In [8]:
# Way Better Solution:
# Boolean Indexing and Filtering
# Create a 1-d array with all multiples of 5 from 15 to 80, and also include 12
# Create a boolean array that identifies elements which are greater than 25
# Use that boolean array to filter out elements greater than 25 from the original array.
arr1 = np.insert(np.arange(15, 81, 5), 0, 12)
print(arr1)
arrbool = arr1 > 25
print("Boolean array: ", arrbool)
print("Filtered to exclude 25: ", arr1[arr1 < 25])
print("Filtered to include 25: ", arr1[arr1 > 25])

[12 15 20 25 30 35 40 45 50 55 60 65 70 75 80]
Boolean array:  [False False False False  True  True  True  True  True  True  True  True
  True  True  True]
Filtered to exclude 25:  [12 15 20]
Filtered to include 25:  [30 35 40 45 50 55 60 65 70 75 80]


In [183]:
#my idea
start = np.zeros((5, 5))
start[0, :] = 1
start[-1,:] = 1
start[:, -1] = 1
start[:, 0] = 1
start[2,2] = 9
#start[1:4,1:4] = 3
print(start)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [139]:
#other idea
start = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
start[1:-1,1:-1] = z
print(start)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [151]:
a  = np.array([1,2,3,4,5])
b = a +5
c = a + 10
d = a + 15
e = a + 20
f = a + 25
arr = np.array([a,b,c,d,e,f])
print(arr)
print(arr[2:4,0:2])
print(arr[[0,1,2,3],[1,2,3,4]])
print(arr[[0,4,5],3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
